export const MOBILE_DESKTOP_BREAKPOINT = 'sm'

export const COLORS = {
  BACKGROUND_GRAY: 'whitesmoke',
  PRIMARY_WHITE: 'white',

  PRIMARY: '#ea6931',
  SECONDARY: '#EB6123',
  ACCENT_PRIMARY: '#512888',
  ACCENT_SECONDARY: '#7349AC',

  ERROR_RED: '#ef5350',
}
